### ISSUE TITLE
MicroSD card switch connection

### ISSUE THREAD

**Issue by charlespax** [micropython/pyboard#10]
I made a copy of the pyboard from the schematic in github, but it would not boot from the SD card. I found an inconsistency between the github schematic and the actual micropython board I purchased.

The [PYBv1.0 schematic](http://micropython.org/resources/PYBv10b.pdf) has the MicroSD card switch connected to PA8 (pin41).
![screen shot 2015-04-30 at 01 23 39](https://cloud.githubusercontent.com/assets/281642/7397158/2444403a-eed9-11e4-9529-76f030e34a46.png)

The schematic in Eagle has the MicroSD card switch connected to PC13 (pin2).
![screen shot 2015-04-30 at 01 21 54](https://cloud.githubusercontent.com/assets/281642/7397263/cbdccca4-eed9-11e4-88c4-d0d4de8d6843.png)

**Comment by charlespax** [comment]
micropython/stmhal/boards/PYBV10/pins.csv has SD and SD_SW both defined at PA8.
![screen shot 2015-04-30 at 13 48 53](https://cloud.githubusercontent.com/assets/281642/7407038/c659012e-ef3f-11e4-8b0f-598809ed4a9b.png)

**Comment by charlespax** [comment]
If I change the MICROPY_HW_SDCARD_DETECT_PIN and load the modified firmware to my board the SD/flash booting works as expected.

```
bash-3.2$ git diff
diff --git a/stmhal/boards/PYBV10/mpconfigboard.h b/stmhal/boards/PYBV10/mpconfigboard.h
index ef4ad10..bd53a22 100644
--- a/stmhal/boards/PYBV10/mpconfigboard.h
+++ b/stmhal/boards/PYBV10/mpconfigboard.h
@@ -53,7 +53,7 @@
 #define MICROPY_HW_LED_OFF(pin)     (pin->gpio->BSRRH = pin->pin_mask)
 
 // SD card detect switch
-#define MICROPY_HW_SDCARD_DETECT_PIN        (pin_A8)
+#define MICROPY_HW_SDCARD_DETECT_PIN        (pin_C13)
 #define MICROPY_HW_SDCARD_DETECT_PULL       (GPIO_PULLUP)
 #define MICROPY_HW_SDCARD_DETECT_PRESENT    (GPIO_PIN_RESET)
```

**Comment by chrismas9** [comment]
The Eagle schematic is for pybv3. There were only 10 hand made boards as early bird prizes. The pdf schematic and the rest of the documentation are for pybv10, the production board. There are other port pin changes as well as SD card switch.

There are separate images available for download for pybv3 and pybv10. Today they are pybv10-2015-04-30-v1.4.2-48-g6f218d7.dfu and pybv3-2015-04-30-v1.4.2-48-g6f218d7.dfu.

If you made your own board from the Eagle schematics and want to build Micro Python from source then make it for the pybv3 board.

**Comment by charlespax** [comment]
Oh boy. I probably should have read the README.md file; it's right there :-)

I'll just redesign my board based on the pybv10 PDF. Are the (Altium?) source files available for the pybv10 board?

**Comment by charlespax** [comment]
@chrismas9 resolved the confusion. Closing issue.
