### ISSUE TITLE
PA10 should be low or high durying boot?

### ISSUE THREAD

**Issue by 1983FFly** [micropython/pyboard#13]
In datasheet of STM32F405xx 2.2.13:
    The boot loader is located in system memory. It is used to reprogram the Flash memory by
using USART1 (PA9/PA10), USART3 (PC10/PC11 or PB10/PB11), CAN2 (PB5/PB13), USB
OTG FS in Device mode (PA11/PA12) through DFU (device firmware upgrade).

PA10:  USART1_RX          pull up by R21 100k
PB11:  USART3_RX          pull up by R12  4k7
PC11:  USART3_RX          pull up by R13 100k

PB5:    CAN2_RX               pull down by R20 100k
PB2:    BOOT1                   pull down by R14 100k 

In PYBv10b.pdf
USB DFU requires stable levels on PA10, PB5, PB11 & PC11. PB2 must be low during boot.
R12, R13, R20 & R21 provide stable input levels for DFU.

**Comment by dpgeorge** [comment]
PA10 must be stable during boot.  It can be high or low, as long as it's a stable logic level.  On pyboard it's pulled high.

**Comment by 1983FFly** [comment]
Thank you!
I am designing a copy for PYBv10b with:
  1:size 50mm x 50mm;
  2:use 0805 resistor & capacitor;
  3:change some small components to lager packaging。
This coyp is easy for rookie to make and test.
