### ISSUE TITLE
executable environment

### ISSUE THREAD

**Issue by PYTOMPY** [micropython/pyboard#16]
Hi everyone,
Im new to micropython and want to convert python code to micropython. Can simple python script running on unix terminal could be converted to micropython? Also we specify !/usr/bin/env pyhton as executable environment for python to specify it to be python script. Is there a way same for micropython? Please give me guideliness how to convert python to micropython in simple way

**Comment by PYTOMPY** [comment]
Also please let me know how do i add micropython in unix terminal.

Thanks in advance,
Gowthami

**Comment by dpgeorge** [comment]
These questions are best asked at https://forum.micropython.org.  In short, you can run MicroPython in a unix terminal by compiling the "unix" port, see ports/unix/ in the main repository, also the README.md in the root of the main repository.

**Comment by PYTOMPY** [comment]
Thank you!. This worked!!
