### ISSUE TITLE
Micropython Board

### ISSUE THREAD

**Issue by PYTOMPY** [micropython/pyboard#17]
Hi all,

1. I want to know how to include micropython in my unix terminal.
2. Do i require pyboard or micropython board to run the micropython code.
3. Cant i run the normal print micropython code or similar small kinds of code on terminal

**Comment by dpgeorge** [comment]
These questions are best asked at https://forum.micropython.org.  You don't need a pyboard to run MicroPython code.  See also https://micropython.org/unicorn/
